### ISSUE TITLE
Edit all SP in Sinh Viên

### ISSUE THREAD

**Issue by hoangsangnguyen** [hoangsang96/CSDL_Phan_Tan#3]
I updated some sp in SINH VIEN WIKI:
- sp_DanhSachSinhVienTheoLop_Insert
- sp_DanhSachSinhVienTheoLop_Update
- sp_DanhSachSinhVienTheoLop_Delete.

Let copy and run in your sql-server.

**Comment by phananh9x** [comment]
Done!
