### ISSUE TITLE
add function in program.cs

### ISSUE THREAD

**Issue by phananh9x** [hoangsang96/CSDL_Phan_Tan#8]
public static DataTable ExecSqlQuery(String cmd)
        {
            DataTable dt1 = new DataTable();
            SqlDataAdapter da = new SqlDataAdapter(cmd, conn);
            da = new SqlDataAdapter(cmd, conn);
            da.Fill(dt1);
            return dt1;
        }

**Comment by hoangsangnguyen** [comment]
done.
